default:
  plugins:
    - textcolor
  language: ja
  toolbar:
    - forecolor | backcolor | styleselect | fontselect
  font_formats:
    "Mincho=IPAexMincho,MS PMincho,Hiragino Mincho Pro;Gothic=IPAexGothic,MS PGothic,Osaka;"
